[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "hubspot.crm.associations"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["ballerina","hubspot","crm", "associations"] 
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.associations"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
